version: "3"
services:
  node-app:
    image: islamahmed94/tresmerge-docker
    env_file:
      - ./.env
    deploy:
      replicas: 4
      #placement:
        #max_replicaas_per_node: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:4.4.6
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  redis:
    image: redis
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./Docker_NodeJS_Nginx/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app

volumes:
  mongo-db:
  #postgres-db: